online/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.cart_add,name="cart_add"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove")
]

online/online/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('',include('shop_cart.urls', namespace='shop')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                         document_root = settings.MEDIA_ROOT)

online/shop_cart/urls.py
from django.urls import path

from . import views

app_name = "shop_cart"

urlpatterns = [
    #url for the Product list
    path('',views.product_list,name="product_list"),
    #url for the Product list by category
    path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),
    #url for the product details
    path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
]

online/cart/models.py
from django.db import models

# Create your models here.

online/shop_cart/models.py
from django.db import models
from django.urls import reverse
class Category(models.Model):
    name =  models.CharField(max_length=200,
                            db_index=True)
    
    slug = models.SlugField(max_length=200,unique=True)

    def get_absolute_url(self):
        return reverse('shop_cart:product_list_by_category',
                        args=[self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category,
                                related_name='products',
                                on_delete = models.CASCADE)
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                             blank=False)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop_cart:product_detail',args=[self.id,self.slug])
    class Meta:
        ordering = ('name',)
        index_together = (('id','slug'))

    def __str__(self):
        return self.name
    

    
    

online/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                        coerce = int)
    override = forms.BooleanField(required = False,
                                    initial = False,
                                    widget = forms.HiddenInput)

online/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop_cart.models import Product

from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                quantity=cd['quantity'],
                override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
                                                                    'quantity':item['quantity'],
                                                                    'override': True})
    return render(request, 'cart/detail.html',{'cart':cart})

online/shop_cart/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Category, Product

# Creating the catalog view
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                 'product/list.html',
                 {'category':category,
                 'categories':categories,
                 'products':products})

# Function view to display a single product
def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                'product/detail.html',
                {'product':product,
                'cart_product_form': cart_product_form})

online/cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Your shopping Cart{% endblock %}

{% block content %}
    <h1>Your Shopping Cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit Price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">    
                                <img src="{% if product.image %}{{ product.image.url }}
                                {% endif %}">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.override }}
                                <input type="submit" value="Update">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="Remove">
                            </form>
                        </td>
                        <td class="num">{{ item.price }} </td>
                        <td class="num">{{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_price }}</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'shop_cart:product_list' %}" class="button light">Continue shopping</a>
        <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
    </p>
{% endblock %}

online/shop_cart/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <title>{% block title %}My Shop{% endblock %}</title>
</head>
<body>
    <div id="header">
        <a href="/" class="logo">My Shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
        {% with total_items=cart|length %}
        {% if total_items > 0 %}
        Your Cart:
        <a href="{% url 'cart:cart_detail' %}">
        {{ total_items }} item{{ total_items|pluralize }},
        ${{ cart.get_total_price }}
        </a>
        {% else %}
            Your Cart is Empty
        {% endif %}
        {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
   
</body>
</html>

online/shop_cart/templates/product/detail.html
{% extends "base.html" %}

{% block title %} {{ product.name }}{% endblock %}

{% block content %}
<div class="product-detail">
    <img src="{% if product.image %} 
                {{ product.image.url }}
              {% endif %}">
    <h1>{{ product.name }}</h1>
    <h3>
        <a href="{{ product.category.get_absolute_url }}">
            {{ product.category }}
        </a>
    </h3>
    <p class="price">${{ product.price }}</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ cart_product_form }}
        <input type="submit" value="Add to cart">
    </form>
    {{ product.description|linebreaks }}
</div>
{% endblock %}

online/shop_cart/templates/product/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}    
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
 <div id="sidebar">
     <h3>Categories</h3>
     <ul>
         <li {% if not category %}class="selected"{% endif %}>
             <a href="{% url 'shop_cart:product_list' %}">All</a>
         </li>
         {% for c in categories %}
         <li {% if category.slug == c.slug %} class="selected" {% endif %}>
             <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
         </li>
         {%  endfor %}
     </ul>
 </div>
 <div id="main" class="product-list">
     <h1>{% if category %}{{ category.name }}{% else %}
         Products{%  endif %}
     </h1>
     {% for product in products %}
        <div class="item">
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/no_image.png' %} {% endif %}" 
            </a>
            <a href="{{ product.get_absolute_url }}">
                {{ product.name }}
            </a>
            <br>
            ${{ product.price }}
        </div>
        {% endfor %}
 </div>
{% endblock %}